logging:
  level:
    root: info
    org.springframework: info
    com.redeyefrog: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss}) %yellow([%thread]) %highlight(%-5level) %logger - %green(%msg%n)"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  transaction:
    rollback-on-commit-failure: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
